### ISSUE TITLE
Blocks don't show up

### ISSUE THREAD

**Issue by Crashone** [InternationalScratchWiki/mw-ScratchBlocks4#14]
Since the last commit ( 7dd5002), the blocks no longer show up.

**Comment by Kenny2github** [comment]
Please provide more information. Can you link us a page where scratchblocks are used? And/or show us an example?

**Comment by Crashone** [comment]
I can't link you a page as it is a private wiki. I can send you a screenshot :
![Screenshot 2022-10-10 at 20-04-46 Modification de Utilisateur Vbesson_bac à sable — Ébulliscience](https://user-images.githubusercontent.com/20670076/194927486-a2b9b312-240b-47ae-8516-c78404df9e69.png)

**Comment by Crashone** [comment]
Thank you, it works !
