### ISSUE TITLE
Scratchblcks not rendering when previewing page

### ISSUE THREAD

**Issue by Ascor8522** [InternationalScratchWiki/mw-ScratchBlocks4#4]
## Actual behavior

On the French Scratch Wiki, when editing a page with Scratchblocks and previewing the changes, the Scratchblocks are not redered.

## Expected behavior

the Scratchblocks should be rendered when previewing the changes made to a page.

## Additional infos
Only ocurring on French Scratch Wiki.
Test on Test Scratch Wiki and it is working as expected.
Working on En Scratch Wiki (I asked about it to some users).

The Scratchblocks scripts are downloaded and loaded.
They are just not triggered.
Scratchblocks are renderd when calling the function by hand in the JavaScript console.
The function is just not called when the preview page is loaded.

Loged in the Fr Scratch Wiki
Using AdBlock (Wiki whitelisted tho)
Using TamperMonkey (no script active, also not working when extension removed)
Google Chrome | 81.0.4044.129
JavaScript | V8 8.1.307.31

**Comment by tjvr** [comment]
I think this has been a bug for years; I never figured it out!

**Comment by Kenny2github** [comment]
After some more recent discoveries - are you using live preview? Live preview doesn't load a new page, and this only executes sb onload. If so, try disabling it and making sure it works then.

**Comment by Ascor8522** [comment]
> After some more recent discoveries - are you using live preview? Live preview doesn't load a new page, and this only executes sb onload. If so, try disabling it and making sure it works then.

Yes, I was using "live preview" (was actuall called "fast preview" in French settings).
When disabled, the page is reloaded and the blocks are displayed as expected.

We probably should add an even listener for page repaint / dom content modified and re-render the scratchblocks.
